### PR TITLE
Update main file from cesium.js to index.js

### PR DESCRIPTION
**Pull request by Griffin1110**
it is driving me slightly mad

### CODE REVIEW

**Comment by thecraptheorist** [comment]
pls
die

**Comment by thecraptheorist** [comment]
i do not appreciate wasting my time on dis

**Comment by thecraptheorist** [comment]
ooo when will i merrrgegeggegeeee

**Comment by thecraptheorist** [comment]
im only doing this cuz im too lazy 2 edit the actual file ;-;

**Comment by Griffin1110** [comment]
i am slowly loosing my sanity

**Pull request merged**
