### PR TITLE
Spelling mistake

### PR DESCRIPTION
**Pull request by jennasisis**
sorry bro. there was a spelling mistake that was driving the absolute shit out of me o.O

### CODE REVIEW

**Comment by thecraptheorist** [comment]
Hey thx for pointing out the typo for me but could you merge that commit into the dbevent-development branch because everything from there is gonna get merged into master eventually

**Comment by thecraptheorist** [comment]
There probably is a way to do it from here but I'm not really good at Github so ;-;

**Comment by Griffin1110** [comment]
_Teamwork In Progress_

**Comment by thecraptheorist** [comment]
Oh well looks like we can squash & merge.
Just found out ;-;

**Pull request merged**
